# Generated by Django 6.0.1 on 2026-05-04 09:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('name_uz', models.CharField(max_length=120, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=120, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=120, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='price')),
                ('currency', models.CharField(default='UZS', max_length=3, verbose_name='currency')),
                ('duration', models.PositiveIntegerField(help_text='Duration units.', verbose_name='duration')),
                ('period', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year'), ('lifetime', 'Lifetime')], default='month', max_length=20, verbose_name='period')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'subscription plan',
                'verbose_name_plural': 'subscription plans',
                'ordering': ('sort_order', 'price'),
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='telegram id')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='last name')),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], default='uz', max_length=2, verbose_name='language')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='is blocked')),
                ('free_tests_taken', models.PositiveSmallIntegerField(default=0, verbose_name='free tests taken')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='last seen at')),
            ],
            options={
                'verbose_name': 'Telegram user',
                'verbose_name_plural': 'Telegram users',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AtmosOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order_id', models.CharField(max_length=64, unique=True, verbose_name='order id')),
                ('atmos_transaction_id', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Atmos transaction id')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('currency', models.CharField(default='UZS', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='created', max_length=20, verbose_name='status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='request payload')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='response payload')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atmos_orders', to='users.subscriptionplan', verbose_name='plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atmos_orders', to='users.telegramuser', verbose_name='user')),
            ],
            options={
                'verbose_name': 'Atmos order',
                'verbose_name_plural': 'Atmos orders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserPremiumSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='starts at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premium_subscriptions', to='users.subscriptionplan', verbose_name='plan')),
                ('source_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_subscription', to='users.atmosorder', verbose_name='source order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_subscriptions', to='users.telegramuser', verbose_name='user')),
            ],
            options={
                'verbose_name': 'premium subscription',
                'verbose_name_plural': 'premium subscriptions',
                'ordering': ('-starts_at',),
            },
        ),
        migrations.CreateModel(
            name='AtmosTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('transaction_id', models.CharField(db_index=True, max_length=128, verbose_name='transaction id')),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('reversed', 'Reversed')], db_index=True, default='initiated', max_length=20, verbose_name='status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('currency', models.CharField(default='UZS', max_length=3, verbose_name='currency')),
                ('provider_payload', models.JSONField(blank=True, default=dict, verbose_name='provider payload')),
                ('performed_at', models.DateTimeField(blank=True, null=True, verbose_name='performed at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.atmosorder', verbose_name='order')),
            ],
            options={
                'verbose_name': 'Atmos transaction',
                'verbose_name_plural': 'Atmos transactions',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['transaction_id', 'status'], name='users_atmos_transac_d0fae8_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'transaction_id'), name='unique_atmos_transaction_per_order')],
            },
        ),
        migrations.AddIndex(
            model_name='atmosorder',
            index=models.Index(fields=['user', 'status'], name='users_atmos_user_id_c90868_idx'),
        ),
        migrations.AddIndex(
            model_name='atmosorder',
            index=models.Index(fields=['order_id', 'status'], name='users_atmos_order_i_da4ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='userpremiumsubscription',
            index=models.Index(fields=['user', 'is_active', 'expires_at'], name='users_userp_user_id_052d55_idx'),
        ),
    ]
