# Generated by Django 6.0.1 on 2026-05-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmosorder',
            name='merchant_order_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='merchant order id'),
        ),
        migrations.AddField(
            model_name='atmosorder',
            name='payment_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='payment url'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='full name'),
        ),
    ]
