# Generated by Django 6.0.5 on 2026-06-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_english_translation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='description_uz_cy',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='name_uz_cy',
            field=models.CharField(max_length=120, null=True, verbose_name='name'),
        ),
    ]
