from tests.models import Test

from .sources import manba_description


def _q(sort_order, level, title_uz, title_ru, question_uz, question_ru, expl_uz, expl_ru, answers, bob, bet):
    return {
        "level": level,
        "sort_order": sort_order,
        "title": {"uz": title_uz, "ru": title_ru},
        "question": {"uz": question_uz, "ru": question_ru},
        "description": manba_description(bob, bet),
        "explanation": {"uz": expl_uz, "ru": expl_ru},
        "answers": answers,
    }


def _a(correct_uz, correct_ru, wrong_uz_ru_pairs):
    opts = [(True, {"uz": correct_uz, "ru": correct_ru})]
    for uz, ru in wrong_uz_ru_pairs:
        opts.append((False, {"uz": uz, "ru": ru}))
    return opts


EASY = Test.Level.EASY
MEDIUM = Test.Level.MEDIUM
HARD = Test.Level.HARD


def get_quiz_questions():
    return [
        # --- 20 EASY (1–20) ---
        _q(1, EASY, "Islomning birinchi rukni", "Первый столп ислама",
           "Islomning birinchi rukni nima?", "Каков первый столп ислама?",
           "Birinchi rukn — iymon va shahodatdir.", "Первый столп — вера и шахада.",
           _a("Shahodat", "Шахада", [("Ro'za", "Пост"), ("Zakot", "Закят"), ("Haj", "Хадж")]), 1, 5),
        _q(2, EASY, "Farz namozlar soni", "Число обязательных молитв",
           "Bir kunda necha mahal farz namoz o'qiladi?", "Сколько обязательных молитв в день?",
           "Kuniga besh mahal farz namoz bor.", "В день пять обязательных молитв.",
           _a("5", "5", [("3", "3"), ("4", "4"), ("7", "7")]), 1, 12),
        _q(3, EASY, "Islom ruknlari", "Столпы ислама",
           "Islom nechta asosiy rukndan iborat?", "Сколько основных столпов в исламе?",
           "Islom beshta rukndan iborat.", "В исламе пять столпов.",
           _a("5", "5", [("4", "4"), ("6", "6"), ("7", "7")]), 1, 18),
        _q(4, EASY, "Qur'on kitobi", "Книга Коран",
           "Musulmonlarning muqaddas kitobi qaysi?", "Какая священная книга у мусульман?",
           "Muqaddas kitob — Qur'oni Karim.", "Священная книга — Коран.",
           _a("Qur'on", "Коран", [("Injil", "Инжил"), ("Tavrot", "Тора"), ("Zabur", "Псалтырь")]), 2, 3),
        _q(5, EASY, "Payg'ambar shahri", "Город пророка",
           "Payg'ambarimiz Muhammad (s.a.v.) qaysi shaharda tug'ilgan?", "В каком городе родился пророк Мухаммад?",
           "U Makka shahrida tug'ilgan.", "Он родился в Мекке.",
           _a("Makka", "Мекка", [("Madina", "Медина"), ("Quddus", "Иерусалим"), ("Tojikiston", "Таджикистан")]), 2, 9),
        _q(6, EASY, "Qibla", "Кибла",
           "Namozda qaysi tomonga yuzlaniladi?", "В какую сторону обращаются в намазе?",
           "Namozda Ka'ba (qibla) tomonga yuzlaniladi.", "В намазе обращаются к Каабе (кибле).",
           _a("Ka'ba tomonga", "К Каабе", [("Sharqqa", "На восток"), ("Shimolga", "На север"), ("G'arbga", "На запад")]), 2, 14),
        _q(7, EASY, "Tahorat", "Омовение",
           "Namozdan oldin qanday tahorat olinadi?", "Какое омовение перед намазом?",
           "Namozdan oldin wudu olinadi.", "Перед намазом совершают вуду.",
           _a("Wudu", "Вуду", [("G'usl", "Гусль"), ("Tayammum", "Таяммум"), ("Hech narsa", "Ничего")]), 2, 20),
        _q(8, EASY, "Fotiha surasi", "Сура Аль-Фатиха",
           "Namozda har rakatda o'qiladigan sura qaysi?", "Какая сура читается в каждом ракате?",
           "Har rakatda Fotiha surasi o'qiladi.", "В каждом ракате читается Аль-Фатиха.",
           _a("Fotiha", "Аль-Фатиха", [("Ixlos", "Ихлас"), ("Kavsar", "Каусар"), ("Nas", "Ан-Нас")]), 3, 2),
        _q(9, EASY, "Ramazon oyi", "Месяц Рамадан",
           "Ro'za tutiladigan muqaddas oy qaysi?", "В каком священном месяце постятся?",
           "Ramazon oyida ro'za tutiladi.", "В месяце Рамадан соблюдают пост.",
           _a("Ramazon", "Рамадан", [("Shavvol", "Шавваль"), ("Rajab", "Раджаб"), ("Muharram", "Мухаррам")]), 3, 8),
        _q(10, EASY, "Zakot", "Закят",
           "Zakot nima?", "Что такое закят?",
           "Zakot — mol-mulkdan beriladigan farz ibodat.", "Закят — обязательная милостыня с имущества.",
           _a("Farz ibodat", "Обязательное действие", [("Sunnat", "Сунна"), ("Makruh", "Макрух"), ("Haram", "Харам")]), 3, 15),
        _q(11, EASY, "Haj", "Хадж",
           "Haj qachon farz bo'ladi?", "Когда хадж становится обязательным?",
           "Imkoniyat bo'lganda umrida bir marta farz.", "При возможности один раз в жизни.",
           _a("Imkoniyat bo'lganda", "При возможности", [("Har yili", "Каждый год"), ("Bolaligida", "В детстве"), ("Ixtiyoriy", "По желанию")]), 3, 22),
        _q(12, EASY, "Kalima shahodat", "Шахада",
           "Shahodat kalimasida nima aytiladi?", "Что говорится в шахаде?",
           "Allohdan boshqa iloh yo'qligi va Muhammad U Zotining rasuli ekanligi.",
           "Нет бога кроме Аллаха, Мухаммад — Его посланник.",
           _a("Alloh bir, Muhammad rasul", "Аллах один, Мухаммад — посланник",
              [("Faqat ro'za", "Только пост"), ("Faqat namoz", "Только намаз"), ("Faqat zakot", "Только закят")]), 4, 4),
        _q(13, EASY, "Shom namozi", "Молитва магриб",
           "Quyosh botgandan keyin o'qiladigan namoz?", "Какая молитва после заката?",
           "Quyosh botgach shom (maghrib) namozi o'qiladi.", "После заката — магриб.",
           _a("Shom (Maghrib)", "Магриб", [("Bomdod", "Фадр"), ("Peshin", "Зухр"), ("Xufton", "Иша")]), 4, 11),
        _q(14, EASY, "Juma namozi", "Пятничная молитва",
           "Juma kuni qaysi namoz jamoat bilan o'qiladi?", "Какая молитва в пятницу с джамаатом?",
           "Juma kuni juma namozi o'qiladi.", "В пятницу — салят аль-джума.",
           _a("Juma namozi", "Джума", [("Tahajjud", "Тахаджуд"), ("Vitir", "Витр"), ("Taroveh", "Таравих")]), 4, 17),
        _q(15, EASY, "Farishtalar", "Ангелы",
           "Farishtalar nima yaratilgan?", "Из чего созданы ангелы?",
           "Farishtalar nurdan yaratilgan.", "Ангелы созданы из света.",
           _a("Nurdan", "Из света", [("Otdan", "Из огня"), ("Tindan", "Из глины"), ("Suvdan", "Из воды")]), 4, 25),
        _q(16, EASY, "Tozalik", "Чистота",
           "Islomda tozalik haqida qanday maqol bor?", "Какое высказывание о чистоте в исламе?",
           "Tozalik iymonning yarmidir.", "Чистота — половина веры.",
           _a("Iymonning yarmi", "Половина веры", [("Iymonning to'liq sharti emas", "Не условие веры"),
              ("Faqat sunnat", "Только сунна"), ("Makruh", "Макрух")]), 5, 6),
        _q(17, EASY, "Bismillah", "Бисмиллях",
           "Har ishni qanday boshlash sunnat?", "Как сунна начинать дела?",
           "Bismillah deb boshlash sunnat.", "Сунна начинать с «Бисмиллях».",
           _a("Bismillah", "Бисмиллях", [("Alhamdulillah", "Альхамдулиллях"), ("Astag'firulloh", "Астагфируллах"),
              ("Subhanalloh", "СубханаЛлах")]), 5, 13),
        _q(18, EASY, "Bomdod rakatlari", "Ракаты фадра",
           "Bomdod namozida necha rakat farz?", "Сколько фард-ракатов в фадре?",
           "Bomdod namozida ikki rakat farz.", "В фадре два фард-раката.",
           _a("2", "2", [("3", "3"), ("4", "4"), ("5", "5")]), 5, 19),
        _q(19, EASY, "Ro'za hayiti", "Ураза-байрам",
           "Ramazon tugagach nima bayram qilinadi?", "Какой праздник после Рамадана?",
           "Ramazondan keyin Ro'za hayiti (Iyd al-Fitr).", "После Рамадана — Ид аль-Фитр.",
           _a("Ro'za hayiti", "Ид аль-Фитр", [("Qurbon hayiti", "Ид аль-Адха"), ("Mavlid", "Мавлид"),
              ("Rajab hayiti", "Раджаб")]), 5, 28),
        _q(20, EASY, "Salom", "Приветствие",
           "Musulmonlar bir-birini qanday salomlashadi?", "Как мусульмане приветствуют друг друга?",
           "Assalomu alaykum deb salomlashiladi.", "Говорят «Ассаляму алейкум».",
           _a("Assalomu alaykum", "Ассаляму алейкум", [("Salom", "Привет"), ("Xayr", "Хайр"),
              ("Rahmat", "Рахмат")]), 5, 30),
        # --- 15 MEDIUM (21–35) ---
        _q(21, MEDIUM, "Namoz shartlari", "Условия намаза",
           "Namozning to'rt shartidan biri qaysi?", "Что из условий намаза?",
           "Tahorat namozning shartlaridan biridir.", "Омовение — одно из условий.",
           _a("Tahorat", "Омовение", [("Ro'za tutmaslik", "Не поститься"), ("Savob", "Награда"),
              ("Sunnat emas", "Не сунна")]), 1, 7),
        _q(22, MEDIUM, "Tayammum", "Таяммум",
           "Tayammum qachon olinadi?", "Когда совершают таяммум?",
           "Suv topilmaganda yoki ishlatib bo'lmaganda.", "Когда нет воды или её нельзя использовать.",
           _a("Suv bo'lmaganda", "Когда нет воды", [("Har namozda", "Каждый намаз"), ("Juma kuni", "В пятницу"),
              ("Faqat kasallikda", "Только при болезни")]), 1, 16),
        _q(23, MEDIUM, "Fajr sunnasi", "Сунна фадра",
           "Bomdoddan oldin o'qiladigan ikki rakat namoz nima?", "Как называются 2 раката до фадра?",
           "Bomdod oldidan ikki rakat sunnat.", "Два раката сунны перед фадром.",
           _a("Bomdod sunnasi", "Сунна фадра", [("Vitir", "Витр"), ("Tahajjud", "Тахаджуд"), ("Juma", "Джума")]), 2, 6),
        _q(24, MEDIUM, "Vitir namozi", "Витр",
           "Xuftondan keyin o'qiladigan wajib namoz?", "Обязательная молитва после иша?",
           "Vitir namozi xuftondan keyin o'qiladi.", "Витр читают после иша.",
           _a("Vitir", "Витр", [("Tahajjud", "Тахаджуд"), ("Duho", "Духа"), ("Taroveh", "Таравих")]), 2, 11),
        _q(25, MEDIUM, "Namozdagi makruh", "Макрух в намазе",
           "Namozda qaysi harakat makruh hisoblanadi?", "Что макрух в намазе?",
           "Namozda ortiqcha harakat qilish makruh.", "Лишние движения в намазе — макрух.",
           _a("Ortiqcha harakat", "Лишние движения", [("Sajda", "Саджда"), ("Ruku", "Руку"),
              ("Takbir", "Такбир")]), 2, 24),
        _q(26, MEDIUM, "Zakot nisobi", "Нисаб закята",
           "Zakot berish uchun mol-mulk qanday miqdorga yetishi kerak?", "Что такое нисаб?",
           "Nisob — zakot chiqadigan minimal miqdor.", "Нисаб — минимум для закята.",
           _a("Minimal miqdor (nisob)", "Нисаб (минимум)", [("Har bir so'm", "Каждый сум"),
              ("Faqat oltin", "Только золото"), ("Zakot shart emas", "Закят не нужен")]), 3, 4),
        _q(27, MEDIUM, "Ro'zani buzadigan", "Нарушители поста",
           "Ro'zani nima buzadi?", "Что нарушает пост?",
           "Ta'm olish va iste'mol qilish ro'zani buzadi.", "Еда и питьё нарушают пост.",
           _a("Ovqat yeyish", "Приём пищи", [("Namoz o'qish", "Намаз"), ("Qur'on o'qish", "Чтение Корана"),
              ("Sadaqa berish", "Садака")]), 3, 10),
        _q(28, MEDIUM, "Hadis turlari", "Виды хадисов",
           "Eng ishonchli hadis qaysi turga kiradi?", "Какой тип хадиса самый достоверный?",
           "Sahih hadis eng ishonchlidir.", "Самые достоверные — сахих.",
           _a("Sahih", "Сахих", [("Mo'zu", "Мавду"), ("Zaif", "Даиф"), ("Mursal", "Мурсаль")]), 3, 17),
        _q(29, MEDIUM, "Ijmo", "Иджма",
           "Ijmo nima?", "Что такое иджма?",
           "Ijmo — ulamolar kelishuvi.", "Иджма — согласие учёных.",
           _a("Ulamolar kelishuvi", "Согласие учёных", [("Shaxsiy fikr", "Личное мнение"),
              ("Qur'on oyati", "Аят Корана"), ("Faqat hadis", "Только хадис")]), 3, 23),
        _q(30, MEDIUM, "Shirk", "Ширк",
           "Shirk nima?", "Что такое ширк?",
           "Shirk — Allohga sherik qo'yish.", "Ширк — придание сотоварищей Аллаху.",
           _a("Sherik qo'yish", "Сотоварищество Аллаху", [("Tawba", "Покаяние"), ("Zikr", "Зикр"),
              ("Namoz", "Намаз")]), 4, 2),
        _q(31, MEDIUM, "G'usl", "Гусль",
           "G'usl qachon farz bo'ladi?", "Когда гусль обязателен?",
           "Janobat va hayz holatidan keyin g'usl farz.", "После полового состояния и менструации.",
           _a("Janobatdan keyin", "После джанабы", [("Har kuni", "Каждый день"), ("Faqat juma", "Только в пятницу"),
              ("Hech qachon", "Никогда")]), 4, 9),
        _q(32, MEDIUM, "Namoz vaqti", "Время намаза",
           "Peshin namozi qachon boshlanadi?", "Когда начинается зухр?",
           "Quyosh zavolga kelgach peshin boshlanadi.", "Зухр — когда солнце проходит зенит.",
           _a("Zavoldan keyin", "После зенита", [("Tongda", "Утром"), ("Quyosh chiqishi", "На восходе"),
              ("Kechasi", "Ночью")]), 4, 14),
        _q(33, MEDIUM, "Azon", "Азан",
           "Azonni kim chiqaradi?", "Кто произносит азан?",
           "Azonni muazzin chiqaradi.", "Азан произносит муэдзин.",
           _a("Muazzin", "Муэдзин", [("Imom", "Имам"), ("Xatib", "Хатиб"), ("Har kim", "Любой")]), 4, 21),
        _q(34, MEDIUM, "Sajda oyatlari", "Аяты саджды",
           "Qur'onda nechta sajda oyati bor?", "Сколько аятов саджды в Коране?",
           "Qur'onda o'n beshta sajda oyati bor (ko'p ulamolar fikri).",
           "По мнению многих учёных — 15 аятов саджды.",
           _a("15", "15", [("5", "5"), ("7", "7"), ("30", "30")]), 5, 3),
        _q(35, MEDIUM, "Wudu tartibi", "Порядок вуду",
           "Wuduning farz amallaridan biri?", "Что из фардов вуду?",
           "Yuzni yuvish wuduning farzidir.", "Мытьё лица — фард вуду.",
           _a("Yuzni yuvish", "Мытьё лица", [("Qo'llarni ikki marta", "Руки дважды всегда"),
              ("Og'izni uchtadan", "Рот 3 раза обязательно"), ("Faqat niyat", "Только намерение")]), 5, 11),
        # --- 15 HARD (36–50) ---
        _q(36, HARD, "Kasal va ro'za", "Болезнь и пост",
           "Og'ir kasal kishiga ro'za qanday?", "Как пост для тяжелобольного?",
           "Og'ir kasal ro'za tutmasligi mumkin, keyin qazo qiladi.", "Может не поститься и восполнить позже.",
           _a("Tutmasligi mumkin, qazo", "Не постится, када", [("Majburan tutadi", "Обязан поститься"),
              ("Hech qachon qazo yo'q", "Без кады"), ("Faqat nafil ro'za", "Только нафиль")]), 1, 8),
        _q(37, HARD, "Arafot kuni", "День Арафат",
           "Hajda eng muhim kun qaysi?", "Главный день хаджа?",
           "Arafot kunida vukuf — hajning asosiy rukni.", "Стояние на Арафате — главное.",
           _a("Arafot", "Арафат", [("Mina", "Мина"), ("Tavof", "Таваф"), ("Sai", "Саи")]), 1, 19),
        _q(38, HARD, "Zakot chiqadigan mol", "Имущество для закята",
           "Zakot qaysi mol-mulkdan chiqadi?", "С какого имущества закят?",
           "O'simlik, chorva, savdo moli va oltin-kumushdan.", "С урожая, скота, торговли, золота и серебра.",
           _a("O'simlik, chorva, savdo, oltin", "Урожай, скот, торговля, золото",
              [("Faqat uy-joy", "Только дом"), ("Faqat mashina", "Только машина"), ("Hech narsadan", "Ни с чего")]), 2, 5),
        _q(39, HARD, "Qazo namoz", "Када намаз",
           "O'tkazib yuborilgan namoz nima deb ataladi?", "Как называется пропущенный намаз?",
           "O'tkazilgan namoz qazo namozi deb o'qiladi.", "Восполняется как када.",
           _a("Qazo", "Када", [("Nafl", "Нафиль"), ("Sunnat", "Сунна"), ("Juma", "Джума")]), 2, 13),
        _q(40, HARD, "Mazhablar", "Мазхабы",
           "Hanafiy mazhab asoschisi kim?", "Основатель ханафитского мазхаба?",
           "Hanafiy mazhabi Imom Abu Hanifa asosida.", "Ханафитский — имам Абу Ханифа.",
           _a("Imom Abu Hanifa", "Имам Абу Ханифа", [("Imom Shofe'i", "Имам Шафии"),
              ("Imom Molik", "Имам Малик"), ("Imom Ahmad", "Имам Ахмад")]), 2, 26),
        _q(41, HARD, "Tahorat turlari", "Виды очищения",
           "Katta najosatdan keyin qanday tahorat?", "Очищение после большой нечистоты?",
           "Katta najosatdan keyin g'usl olinadi.", "После большой нечистоты — гусль.",
           _a("G'usl", "Гусль", [("Wudu", "Вуду"), ("Tayammum", "Таяммум"), ("Faqat namoz", "Только намаз")]), 3, 1),
        _q(42, HARD, "Qiyos", "Кияс",
           "Fiqhda qiyos nima?", "Что такое кияс в фикхе?",
           "Qiyos — hukmni o'xshash masalaga qo'llash.", "Кияс — перенос суждения на похожий случай.",
           _a("O'xshashga qo'llash", "Перенос на похожее", [("Ijmo bekor", "Отмена иджмы"),
              ("Hadis yo'q", "Нет хадиса"), ("Shaxsiy arzu", "Личное желание")]), 3, 7),
        _q(43, HARD, "Ihrom", "Ихрам",
           "Ihromda erkaklar uchun qaysi kiyim taqiqlanadi?", "Что запрещено мужчинам в ихраме?",
           "Ihromda tikilgan kiyim taqiqlanadi (erkaklar uchun).", "Мужчинам запречена обычная шитая одежда.",
           _a("Tikilgan kiyim", "Шитая одежда", [("Oq irk", "Белый ихрам"), ("Sandals", "Сандалии"),
              ("Ko'ylak", "Рубашка")]), 3, 14),
        _q(44, HARD, "Oydinlik", "Сighting луны",
           "Ramazon boshlanishi qanday aniqlanadi?", "Как определяют начало Рамадана?",
           "Ramazon oyining ko'rinishi (hilol) bilan.", "По появлению новолуния (хиляль).",
           _a("Hilol ko'rinishi", "Новолуние", [("G'arb taqvimi", "Только западный календарь"),
              ("Imom xohishi", "Желание имама"), ("Doim 1-mart", "Всегда 1 марта")]), 3, 20),
        _q(45, HARD, "Nikoh", "Брак",
           "Nikohda necha guvoh bo'lishi kerak?", "Сколько свидетелей в никяхе?",
           "Nikohda kamida ikki adol guvoh kerak (Hanafiy fikhi).", "Минимум два справедливых свидетеля.",
           _a("Ikki guvoh", "Два свидетеля", [("Bir guvoh", "Один"), ("Guvoh shart emas", "Не нужны"),
              ("Faqat vali", "Только опекун")]), 4, 6),
        _q(46, HARD, "Halol go'sht", "Халяльное мясо",
           "Go'sht halol bo'lishi uchun nima kerak?", "Что нужно для халяльного мяса?",
           "Islom qoidalariga muvofiq so'yilgan bo'lishi kerak.", "Забой по исламским правилам.",
           _a("Islomiy usulda so'yish", "Забой по шариату", [("Har qanday hayvon", "Любое животное"),
              ("Faqat baliq", "Только рыба"), ("Faqat qush", "Только птица")]), 4, 12),
        _q(47, HARD, "Riba", "Риба",
           "Riba (foiz) haqida Islom qanday hukm beradi?", "Какой хукм у рибы (процента)?",
           "Riba qat'iyan harom hisoblanadi.", "Риба строго харам.",
           _a("Harom", "Харам", [("Halol", "Халяль"), ("Muboh", "Мубах"), ("Makruh", "Макрух")]), 4, 18),
        _q(48, HARD, "Kaffora", "Каффара",
           "Ramazon ro'zasini ataylab buzgan kishi nima qiladi?", "Что делает нарушивший пост Рамадана намеренно?",
           "Kaffora: qazo + 60 kun ketma-ket ro'za yoki 60 kambag'alga taom (Hanafiy).",
           "Каффара: када + 60 дней поста или кормление 60 бедняков.",
           _a("Qazo va kaffora", "Када и каффара", [("Faqat kechirish", "Только прощение"),
              ("Hech narsa emas", "Ничего"), ("Faqat sadaqa", "Только садака")]), 4, 24),
        _q(49, HARD, "Idtiror", "Идтарор",
           "Idtiror (majburiyat) holatida hukm qanday?", "Какой хукм при идтарор?",
           "Zarurat holatida ruxsat berilishi mumkin.", "При крайней необходимости допускается облегчение.",
           _a("Zaruratda ruxsat", "Допускается при нужде", [("Har doim qat'iy", "Всегда строго"),
              ("Harom bo'lib qoladi", "Становится харам"), ("Faqat sunnat", "Только сунна")]), 5, 5),
        _q(50, HARD, "Shahodat qabul", "Принятие шахады",
           "Shahodat qabul qilish uchun asosiy shart?", "Главное условие принятия шахады?",
           "Kishi haqiqiy ixlos va tilovat bilan aytishi kerak.", "Искренность и произнесение слов.",
           _a("Ixlos va tilovat", "Искренность и произнесение", [("Faqat yozma", "Только письменно"),
              ("Faqat ko'ngildan", "Только в сердце"), ("Guvohsiz", "Без свидетелей")]), 5, 16),
    ]
