JAZZMIN_SETTINGS = {
    "site_title": "Deenify",
    "site_header": "Deenify boshqaruv",
    "site_brand": "Deenify",
    "site_logo": None,
    "login_logo": None,
    "welcome_sign": "Boshqaruv paneliga xush kelibsiz",
    "copyright": "Deenify",
    "search_model": ["users.TelegramUser", "tests.Test"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Bosh sahifa", "url": "admin:index", "permissions": ["auth.view_user"]},
        {
            "name": "JSON dan yuklash",
            "url": "admin:tests_test_import_json",
            "permissions": ["tests.add_test"],
        },
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": ["tests.TestCategory"],
    "order_with_respect_to": ["users", "tests", "auth"],
    "icons": {
        "auth": "fas fa-shield-alt",
        "auth.user": "fas fa-user-shield",
        "auth.Group": "fas fa-users",
        "users.TelegramUser": "fas fa-paper-plane",
        "users.ActiveTelegramUser": "fas fa-user-check",
        "users.SubscriptionPlan": "fas fa-gem",
        "users.UserPremiumSubscription": "fas fa-star",
        "users.AtmosOrder": "fas fa-receipt",
        "users.AtmosTransaction": "fas fa-exchange-alt",
        "tests.Test": "fas fa-book-quran",
        "tests.Answer": "fas fa-list-ul",
        "tests.UserAnsweredTest": "fas fa-check-double",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": "admin/css/deenify_admin.css",
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "users.telegramuser": "collapsible",
        "tests.test": "collapsible",
        "tests.answer": "collapsible",
        "users.subscriptionplan": "collapsible",
    },
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "cerulean",
    "dark_mode_theme": None,
    "navbar": "navbar-dark navbar-primary",
    "sidebar": "sidebar-dark-primary elevation-4",
    "accent": "accent-primary",
    "brand_colour": "navbar-primary",
    "footer_fixed": False,
    "body_small_text": False,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
