"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv(override=True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.getenv("SECRET_KEY", "dev-secret-key")
DEBUG = os.getenv("DEBUG", "True") == "True"
ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'modeltranslation',
    'rest_framework',
    'drf_spectacular',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',
    'tests.apps.TestsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

_database_url = os.getenv('DATABASE_URL', '').strip()
if _database_url:
    import dj_database_url

    DATABASES['default'] = dj_database_url.parse(
        _database_url,
        conn_max_age=600,
        conn_health_checks=True,
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

from django.conf.locale import LANG_INFO

# modeltranslation uses uz_cy — Django must know this code in LANG_INFO + LANGUAGES
LANG_INFO.update(
    {
        "uz_cy": {
            "bidi": False,
            "code": "uz-cy",
            "name": "Uzbek Cyrillic",
            "name_local": "Ўзбекча",
        },
    }
)

LANGUAGE_CODE = 'uz'

# modeltranslation: barcha tillar LANGUAGES da bo'lishi kerak (uz_cy — kirill)
LANGUAGES = (
    ('uz', "O'zbekcha (lotin)"),
    ('uz_cy', 'Ўзбекча (kirill)'),
    ('ru', 'Ruscha'),
)

# Django 6 rasmiy ro'yxatda uz_cy yo'q; modeltranslation uchun kerak
SILENCED_SYSTEM_CHECKS = ['translation.E002']

LOCALE_PATHS = [BASE_DIR / 'locale']

MODELTRANSLATION_DEFAULT_LANGUAGE = 'uz'
MODELTRANSLATION_LANGUAGES = ('uz', 'uz_cy', 'ru')
MODELTRANSLATION_FALLBACK_LANGUAGES = ('uz', 'ru', 'uz_cy')

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Deenify API',
    'DESCRIPTION': 'Telegram bot, quiz va to\'lov API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'TAGS': [
        {'name': 'bot-users', 'description': 'Telegram foydalanuvchilar'},
        {'name': 'quiz', 'description': 'Test savollari'},
        {'name': 'subscriptions', 'description': 'Obuna rejalari'},
        {'name': 'payments', 'description': 'Atmos to\'lovlar'},
        {'name': 'admin', 'description': 'Admin statistika'},
    ],
}

from config.jazzmin_settings import JAZZMIN_SETTINGS, JAZZMIN_UI_TWEAKS  # noqa: E402

ATMOS_STORE_ID = os.environ.get('ATMOS_STORE_ID', '')
ATMOS_TERMINAL_ID = os.environ.get('ATMOS_TERMINAL_ID', '')
ATMOS_CONSUMER_KEY = os.environ.get('ATMOS_CONSUMER_KEY', '')
ATMOS_CONSUMER_SECRET = os.environ.get('ATMOS_CONSUMER_SECRET', '')
ATMOS_API_KEY = os.environ.get('ATMOS_API_KEY', '')
ATMOS_CALLBACK_URL = os.environ.get('ATMOS_CALLBACK_URL', '')
ATMOS_RETURN_URL = os.environ.get('ATMOS_RETURN_URL', '')
ATMOS_BASE_URL = os.environ.get('ATMOS_BASE_URL', 'https://apigw.atmos.uz')
ATMOS_CHECKOUT_URL = os.environ.get('ATMOS_CHECKOUT_URL', 'https://checkout.pays.uz/invoice/get')
ATMOS_SIGN_ALGORITHM = os.environ.get('ATMOS_SIGN_ALGORITHM', 'sha256')

# Quiz (Telegram bot round-based flow)
DEENIFY_QUIZ_DEFAULT_CATEGORY_SLUG = os.environ.get('DEENIFY_QUIZ_DEFAULT_CATEGORY_SLUG', 'islam')
DEENIFY_QUIZ_FIRST_ROUND_EASY_COUNT = int(
    os.environ.get('DEENIFY_QUIZ_FIRST_ROUND_EASY_COUNT', '10')
)
DEENIFY_QUIZ_SUBSCRIPTION_REQUIRED = (
    os.environ.get('DEENIFY_QUIZ_SUBSCRIPTION_REQUIRED', 'False') == 'True'
)
