from django.urls import path

from .views import (
    AdminStatisticsView,
    AtmosCallbackView,
    AtmosCardApplyView,
    AtmosCardPreApplyView,
    AtmosCardSetLanguageView,
    AtmosCheckoutRedirectView,
    AtmosOrderCreateView,
    AtmosPaymentStartView,
    AtmosReturnView,
    BotUserBotActiveView,
    BotUserCancelSubscriptionView,
    BotUserDetailView,
    BotUserFeedbackView,
    BotUserLanguageView,
    BotUserOfferMessageView,
    BotUserOrdersView,
    BotUserReferralView,
    BotUserStatisticsView,
    BotUserView,
    SubscriptionPlanListView,
)

urlpatterns = [
    path("api/v1/bot/users/", BotUserView.as_view(), name="bot-user-upsert"),
    path(
        "api/v1/bot/users/<int:telegram_id>/",
        BotUserDetailView.as_view(),
        name="bot-user-detail",
    ),
    path(
        "api/v1/bot/users/<int:telegram_id>/language/",
        BotUserLanguageView.as_view(),
        name="bot-user-language",
    ),
    path(
        "api/v1/bot/users/<int:telegram_id>/bot-active/",
        BotUserBotActiveView.as_view(),
        name="bot-user-bot-active",
    ),
    path(
        "api/v1/bot/users/<int:telegram_id>/offer-message/",
        BotUserOfferMessageView.as_view(),
        name="bot-user-offer-message",
    ),
    path(
        "api/v1/bot/users/<int:telegram_id>/statistics/",
        BotUserStatisticsView.as_view(),
        name="bot-user-statistics",
    ),
    path(
        "api/v1/bot/users/<int:telegram_id>/referral/",
        BotUserReferralView.as_view(),
        name="bot-user-referral",
    ),
    path(
        "api/v1/bot/users/<int:telegram_id>/cancel-subscription/",
        BotUserCancelSubscriptionView.as_view(),
        name="bot-user-cancel-subscription",
    ),
    path(
        "api/v1/bot/users/<int:telegram_id>/feedback/",
        BotUserFeedbackView.as_view(),
        name="bot-user-feedback",
    ),
    path(
        "api/v1/bot/users/<int:telegram_id>/orders/",
        BotUserOrdersView.as_view(),
        name="bot-user-orders",
    ),
    path(
        "api/v1/subscriptions/plans/",
        SubscriptionPlanListView.as_view(),
        name="subscription-plan-list",
    ),
    path(
        "api/v1/payments/atmos/orders/",
        AtmosOrderCreateView.as_view(),
        name="atmos-order-create",
    ),
    path(
        "api/v1/payments/atmos/callback/",
        AtmosCallbackView.as_view(),
        name="atmos-callback",
    ),
    path(
        "api/v1/payments/atmos/return/",
        AtmosReturnView.as_view(),
        name="atmos-return",
    ),
    path(
        "api/v1/payments/atmos/start/",
        AtmosPaymentStartView.as_view(),
        name="atmos-payment-start",
    ),
    path(
        "api/v1/payments/atmos/card/pre-apply/",
        AtmosCardPreApplyView.as_view(),
        name="atmos-card-preapply",
    ),
    path(
        "api/v1/payments/atmos/card/apply/",
        AtmosCardApplyView.as_view(),
        name="atmos-card-apply",
    ),
    path(
        "api/v1/payments/atmos/card/set-language/",
        AtmosCardSetLanguageView.as_view(),
        name="atmos-card-set-language",
    ),
    path(
        "api/v1/payments/atmos/checkout/<str:order_id>/",
        AtmosCheckoutRedirectView.as_view(),
        name="atmos-checkout-redirect",
    ),
    path(
        "api/v1/admin/statistics/",
        AdminStatisticsView.as_view(),
        name="admin-statistics",
    ),
]
