from django.urls import path

from .views import (
    AdminStatisticsView,
    BotUserBotActiveView,
    BotUserCancelSubscriptionView,
    BotUserDetailView,
    BotUserFeedbackView,
    BotUserLanguageView,
    BotUserOfferMessageView,
    BotUserOrdersView,
    BotUserReferralView,
    BotUserStatisticsView,
    BotUserView,
    ClickCallbackView,
    ClickOrderCheckoutView,
    ClickOrderCreateView,
    ClickPaymentStartView,
    ClickReturnView,
    SubscriptionPlanListView,
)

urlpatterns = [
    path("api/v1/bot/users/", BotUserView.as_view(), name="bot-user-upsert"),
    path(
        "api/v1/bot/users/<int:telegram_id>/",
        BotUserDetailView.as_view(),
        name="bot-user-detail",
    ),
    path(
        "api/v1/bot/users/<int:telegram_id>/language/",
        BotUserLanguageView.as_view(),
        name="bot-user-language",
    ),
    path(
        "api/v1/bot/users/<int:telegram_id>/bot-active/",
        BotUserBotActiveView.as_view(),
        name="bot-user-bot-active",
    ),
    path(
        "api/v1/bot/users/<int:telegram_id>/offer-message/",
        BotUserOfferMessageView.as_view(),
        name="bot-user-offer-message",
    ),
    path(
        "api/v1/bot/users/<int:telegram_id>/statistics/",
        BotUserStatisticsView.as_view(),
        name="bot-user-statistics",
    ),
    path(
        "api/v1/bot/users/<int:telegram_id>/referral/",
        BotUserReferralView.as_view(),
        name="bot-user-referral",
    ),
    path(
        "api/v1/bot/users/<int:telegram_id>/cancel-subscription/",
        BotUserCancelSubscriptionView.as_view(),
        name="bot-user-cancel-subscription",
    ),
    path(
        "api/v1/bot/users/<int:telegram_id>/feedback/",
        BotUserFeedbackView.as_view(),
        name="bot-user-feedback",
    ),
    path(
        "api/v1/bot/users/<int:telegram_id>/orders/",
        BotUserOrdersView.as_view(),
        name="bot-user-orders",
    ),
    path(
        "api/v1/subscriptions/plans/",
        SubscriptionPlanListView.as_view(),
        name="subscription-plan-list",
    ),
    path(
        "api/v1/payments/click/orders/",
        ClickOrderCreateView.as_view(),
        name="click-order-create",
    ),
    path(
        "api/v1/payments/click/start/",
        ClickPaymentStartView.as_view(),
        name="click-payment-start",
    ),
    path(
        "api/v1/payments/click/checkout/<str:order_id>/",
        ClickOrderCheckoutView.as_view(),
        name="click-order-checkout",
    ),
    path(
        "api/v1/payments/click/callback/",
        ClickCallbackView.as_view(),
        name="click-callback",
    ),
    path(
        "api/v1/payments/click/return/",
        ClickReturnView.as_view(),
        name="click-return",
    ),
    path(
        "api/v1/admin/statistics/",
        AdminStatisticsView.as_view(),
        name="admin-statistics",
    ),
]
