DEFAULT_LANGUAGE = "uz"
SUPPORTED_LANGUAGES = {"uz", "ru", "en"}


TEXTS = {
    "uz": {
        "choose_language": "Tilni tanlang:",
        "main_menu": "Asosiy menyu",
        "take_test": "🧪 Test yechish",
        "profile": "👤 Profil",
        "buy_premium": "💳 Premium olish",
        "change_language": "🌐 Tilni o‘zgartirish",
        "language_updated": "Til yangilandi.",
        "free_limit_finished": "Bepul testlar limiti tugadi. Davom etish uchun Premium oling.",
        "choose_test_type": "Test turini tanlang:",
        "easy": "Easy",
        "medium": "Medium",
        "hard": "Hard",
        "mixed": "Mixed",
        "no_questions": "Hozircha savollar topilmadi.",
        "correct": "✅ To‘g‘ri!",
        "wrong": "❌ Noto‘g‘ri.",
        "final_result": "Natija:\n✅ To‘g‘ri: {correct}\n❌ Noto‘g‘ri: {wrong}\n📌 Jami: {total}\n📊 Foiz: {score}%",
        "back_menu": "⬅️ Menyuga qaytish",
        "plans": "Premium tarifni tanlang:",
        "payment_text": "To‘lovni amalga oshiring. To‘lovdan keyin premium avtomatik ochiladi.",
        "pay": "💳 To‘lash",
        "check_premium": "✅ Tekshirish",
        "premium_active": "✅ Premium faol.",
        "premium_inactive": "Premium hali faol emas.",
        "blocked": "Akkount bloklangan.",
        "not_found": "Ma’lumot topilmadi.",
        "error": "Xatolik yuz berdi. Keyinroq urinib ko‘ring.",
        "profile_text": "👤 Profil\n\nPremium: {premium}\nPremium muddati: {premium_until}\nBepul testlar: {free_used}/10\nSessiyalar: {sessions}\nJavoblar: {answers}\nTo‘g‘ri: {correct}\nNoto‘g‘ri: {wrong}\nFoiz: {score}%",
        "yes": "Ha",
        "no": "Yo‘q",
        "unlimited": "Cheksiz",
    },
    "ru": {
        "choose_language": "Выберите язык:",
        "main_menu": "Главное меню",
        "take_test": "🧪 Пройти тест",
        "profile": "👤 Профиль",
        "buy_premium": "💳 Купить Premium",
        "change_language": "🌐 Изменить язык",
        "language_updated": "Язык обновлен.",
        "free_limit_finished": "Лимит бесплатных тестов закончился. Купите Premium, чтобы продолжить.",
        "choose_test_type": "Выберите тип теста:",
        "easy": "Easy",
        "medium": "Medium",
        "hard": "Hard",
        "mixed": "Mixed",
        "no_questions": "Вопросы пока не найдены.",
        "correct": "✅ Правильно!",
        "wrong": "❌ Неправильно.",
        "final_result": "Результат:\n✅ Правильно: {correct}\n❌ Неправильно: {wrong}\n📌 Всего: {total}\n📊 Процент: {score}%",
        "back_menu": "⬅️ В меню",
        "plans": "Выберите Premium тариф:",
        "payment_text": "Оплатите заказ. После оплаты Premium включится автоматически.",
        "pay": "💳 Оплатить",
        "check_premium": "✅ Проверить",
        "premium_active": "✅ Premium активен.",
        "premium_inactive": "Premium пока не активен.",
        "blocked": "Аккаунт заблокирован.",
        "not_found": "Данные не найдены.",
        "error": "Произошла ошибка. Попробуйте позже.",
        "profile_text": "👤 Профиль\n\nPremium: {premium}\nPremium до: {premium_until}\nБесплатные тесты: {free_used}/10\nСессии: {sessions}\nОтветы: {answers}\nПравильно: {correct}\nНеправильно: {wrong}\nПроцент: {score}%",
        "yes": "Да",
        "no": "Нет",
        "unlimited": "Без срока",
    },
    "en": {
        "choose_language": "Choose language:",
        "main_menu": "Main menu",
        "take_test": "🧪 Take test",
        "profile": "👤 Profile",
        "buy_premium": "💳 Buy Premium",
        "change_language": "🌐 Change language",
        "language_updated": "Language updated.",
        "free_limit_finished": "Your free test limit is finished. Buy Premium to continue.",
        "choose_test_type": "Choose test type:",
        "easy": "Easy",
        "medium": "Medium",
        "hard": "Hard",
        "mixed": "Mixed",
        "no_questions": "No questions found yet.",
        "correct": "✅ Correct!",
        "wrong": "❌ Wrong.",
        "final_result": "Result:\n✅ Correct: {correct}\n❌ Wrong: {wrong}\n📌 Total: {total}\n📊 Score: {score}%",
        "back_menu": "⬅️ Back to menu",
        "plans": "Choose a Premium plan:",
        "payment_text": "Complete the payment. Premium will activate automatically after payment.",
        "pay": "💳 Pay",
        "check_premium": "✅ Check",
        "premium_active": "✅ Premium is active.",
        "premium_inactive": "Premium is not active yet.",
        "blocked": "Account is blocked.",
        "not_found": "Data not found.",
        "error": "Something went wrong. Try again later.",
        "profile_text": "👤 Profile\n\nPremium: {premium}\nPremium until: {premium_until}\nFree tests: {free_used}/10\nSessions: {sessions}\nAnswers: {answers}\nCorrect: {correct}\nWrong: {wrong}\nScore: {score}%",
        "yes": "Yes",
        "no": "No",
        "unlimited": "Unlimited",
    },
}


def normalize_language(language):
    return language if language in SUPPORTED_LANGUAGES else DEFAULT_LANGUAGE


def get_text(language, key, **kwargs):
    language = normalize_language(language)
    template = TEXTS[language].get(key, TEXTS[DEFAULT_LANGUAGE].get(key, key))
    return template.format(**kwargs) if kwargs else template
