# Generated by Django 6.0.1 on 2026-05-04 09:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('question', models.TextField(verbose_name='question')),
                ('question_uz', models.TextField(null=True, verbose_name='question')),
                ('question_ru', models.TextField(null=True, verbose_name='question')),
                ('question_en', models.TextField(null=True, verbose_name='question')),
                ('explanation', models.TextField(blank=True, verbose_name='explanation')),
                ('explanation_uz', models.TextField(blank=True, null=True, verbose_name='explanation')),
                ('explanation_ru', models.TextField(blank=True, null=True, verbose_name='explanation')),
                ('explanation_en', models.TextField(blank=True, null=True, verbose_name='explanation')),
                ('level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='easy', max_length=10, verbose_name='level')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_premium', models.BooleanField(default=False, verbose_name='is premium')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'test',
                'verbose_name_plural': 'tests',
                'ordering': ('category', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=160, verbose_name='name')),
                ('name_uz', models.CharField(max_length=160, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=160, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=160, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'test category',
                'verbose_name_plural': 'test categories',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('text', models.CharField(max_length=500, verbose_name='text')),
                ('text_uz', models.CharField(max_length=500, null=True, verbose_name='text')),
                ('text_ru', models.CharField(max_length=500, null=True, verbose_name='text')),
                ('text_en', models.CharField(max_length=500, null=True, verbose_name='text')),
                ('is_correct', models.BooleanField(db_index=True, default=False, verbose_name='is correct')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.test', verbose_name='test')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='tests.testcategory', verbose_name='category'),
        ),
        migrations.CreateModel(
            name='UserTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('level', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, max_length=10, verbose_name='level')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='started', max_length=20, verbose_name='status')),
                ('total_questions', models.PositiveSmallIntegerField(default=0, verbose_name='total questions')),
                ('correct_answers', models.PositiveSmallIntegerField(default=0, verbose_name='correct answers')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='tests.testcategory', verbose_name='category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='users.telegramuser', verbose_name='user')),
            ],
            options={
                'verbose_name': 'user test session',
                'verbose_name_plural': 'user test sessions',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='UserTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_correct', models.BooleanField(db_index=True, default=False, verbose_name='is correct')),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='answered at')),
                ('selected_answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_answers', to='tests.answer', verbose_name='selected answer')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_answers', to='tests.test', verbose_name='test')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='tests.usertestsession', verbose_name='session')),
            ],
            options={
                'verbose_name': 'user test answer',
                'verbose_name_plural': 'user test answers',
                'ordering': ('answered_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('test',), name='unique_correct_answer_per_test'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['category', 'level', 'is_active'], name='tests_test_categor_8d260f_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestsession',
            index=models.Index(fields=['user', 'status'], name='tests_usert_user_id_a3b249_idx'),
        ),
        migrations.AddIndex(
            model_name='usertestsession',
            index=models.Index(fields=['category', 'level'], name='tests_usert_categor_087be0_idx'),
        ),
        migrations.AddConstraint(
            model_name='usertestanswer',
            constraint=models.UniqueConstraint(fields=('session', 'test'), name='unique_answer_per_test_in_session'),
        ),
    ]
