# Generated by Django 6.0.1 on 2026-05-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestsession',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='test_sessions', to='tests.test', verbose_name='tests'),
        ),
        migrations.AddField(
            model_name='usertestsession',
            name='wrong_answers',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='wrong answers'),
        ),
    ]
