# Generated by Django 6.0.5 on 2026-05-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_test_description'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='useransweredtest',
            new_name='tests_usera_user_id_f0cb0b_idx',
            old_name='tests_usera_user_id_6e8f0d_idx',
        ),
        migrations.AddField(
            model_name='answer',
            name='text_uz_cy',
            field=models.CharField(max_length=500, null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='test',
            name='explanation_uz_cy',
            field=models.TextField(blank=True, help_text='Short feedback after the user answers (not shown in the poll).', null=True, verbose_name='explanation'),
        ),
        migrations.AddField(
            model_name='test',
            name='question_uz_cy',
            field=models.TextField(null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='test',
            name='title_uz_cy',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='description_uz_cy',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='name_uz_cy',
            field=models.CharField(max_length=160, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description_ru',
            field=models.TextField(blank=True, help_text='Source citation shown in Telegram quiz poll (not the answer explanation).', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description_uz',
            field=models.TextField(blank=True, help_text='Source citation shown in Telegram quiz poll (not the answer explanation).', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description_uz_cy',
            field=models.TextField(blank=True, help_text='Source citation shown in Telegram quiz poll (not the answer explanation).', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='test',
            name='explanation',
            field=models.TextField(blank=True, help_text='Short feedback after the user answers (not shown in the poll).', verbose_name='explanation'),
        ),
        migrations.AlterField(
            model_name='test',
            name='explanation_ru',
            field=models.TextField(blank=True, help_text='Short feedback after the user answers (not shown in the poll).', null=True, verbose_name='explanation'),
        ),
        migrations.AlterField(
            model_name='test',
            name='explanation_uz',
            field=models.TextField(blank=True, help_text='Short feedback after the user answers (not shown in the poll).', null=True, verbose_name='explanation'),
        ),
    ]
