# Generated by Django 6.0.5 on 2026-06-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_remove_legacy_test_session_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='level',
            field=models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rta"), ('hard', 'Qiyin')], db_index=True, default='easy', max_length=10, verbose_name='level'),
        ),
    ]
